<div style="border-style:groove;border-width:thin;padding:10px">
    <h3>EJERCICIO 1:</h3>
</div>

In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
import pandas as pd
peliculas = pd.read_csv('peliculas.csv')
peliculas.head(2)

,budget,genres,homepage,id,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"['Action', 'Adventure', 'Fantasy', 'Science Fi...",http://www.avatarmovie.com/,19995,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"['Ingenious Film Partners', 'Twentieth Century...",2009-12-10,2787965087,162.0,"['English', 'Español']",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"['Adventure', 'Fantasy', 'Action']",http://disney.go.com/disneypictures/pirates/,285,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"['Walt Disney Pictures', 'Jerry Bruckheimer Fi...",2007-05-19,961000000,169.0,['English'],Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [3]:
import ast
peliculas['genres'] = peliculas['genres'].apply(ast.literal_eval)
peliculas['production_companies'] = peliculas['production_companies'].apply(ast.literal_eval)
peliculas['spoken_languages'] = peliculas['spoken_languages'].apply(ast.literal_eval)

In [4]:
peliculas = peliculas.drop(columns=["homepage", "original_language", "original_title", "release_date", "id", "overview", "tagline"])

In [5]:
peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   popularity            4803 non-null   float64
 3   production_companies  4803 non-null   object
 4   revenue               4803 non-null   int64
 5   runtime               4801 non-null   float64
 6   spoken_languages      4803 non-null   object
 7   status                4803 non-null   object
 8   title                 4803 non-null   object
 9   vote_average          4803 non-null   float64
 10  vote_count            4803 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 412.9+ KB

In [6]:
peliculas["genres"] = peliculas["genres"].to_frame()

In [7]:
'''
#['Comedy', 'Adventure', 'Fantasy', 'Animation', 'Family', 'Drama', 'Action', 'Horror']
#'English', 'Español', 'Italiano', 'Français', 'Deutsch'
genero = []

#'English', 'Español', 'Italiano', 'Français', 'Deutsch'
generos = []
for index,row in peliculas.iterrows():
    peliculas['genres'].str.split(',', expand=True)  
    generos.append()


peliculas['Unemployment rate'] = Unemployment_rate
estudiantes['Inflation rate'] = Inflation_rate

#peliculas['Comedy'] = comedy
#peliculas['Adventure'] = adventure

#col = df_obesidad.pop('Indice') # 1. Extraer la columna
#df_obesidad.insert(0, 'Indice', col) # 2. Insertar en la posición 0
'''

"\n#['Comedy', 'Adventure', 'Fantasy', 'Animation', 'Family', 'Drama', 'Action', 'Horror']\n#'English', 'Español', 'Italiano', 'Français', 'Deutsch'\ngenero = []\n\n#'English', 'Español', 'Italiano', 'Français', 'Deutsch'\ngeneros = []\nfor index,row in peliculas.iterrows():\n    peliculas['genres'].str.split(',', expand=True)  \n    generos.append()\n\n\npeliculas['Unemployment rate'] = Unemployment_rate\nestudiantes['Inflation rate'] = Inflation_rate\n\n#peliculas['Comedy'] = comedy\n#peliculas['Adventure'] = adventure\n\n#col = df_obesidad.pop('Indice') # 1. Extraer la columna\n#df_obesidad.insert(0, 'Indice', col) # 2. Insertar en la posición 0\n"

In [8]:
'''
Unemployment_rate = []
Inflation_rate = []

for row in peliculas.iterrows():
    Unemployment_rate = peliculas["Unemployment rate"].str.replace("[", "").astype(float)
    Inflation_rate = peliculas["Inflation rate"].str.replace("]", "").astype(float) 

peliculas['Unemployment rate'] = Unemployment_rate
peliculas['Inflation rate'] = Inflation_rate

peliculas.head()

'''

'\nUnemployment_rate = []\nInflation_rate = []\n\nfor row in peliculas.iterrows():\n    Unemployment_rate = peliculas["Unemployment rate"].str.replace("[", "").astype(float)\n    Inflation_rate = peliculas["Inflation rate"].str.replace("]", "").astype(float) \n\npeliculas[\'Unemployment rate\'] = Unemployment_rate\npeliculas[\'Inflation rate\'] = Inflation_rate\n\npeliculas.head()\n\n'

In [9]:
# No se hacerlo, elimino las columnas:

peliculas = peliculas.drop(columns = ["genres", "production_companies", "spoken_languages", "title"])

In [10]:
peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   budget        4803 non-null   int64
 1   popularity    4803 non-null   float64
 2   revenue       4803 non-null   int64
 3   runtime       4801 non-null   float64
 4   status        4803 non-null   object
 5   vote_average  4803 non-null   float64
 6   vote_count    4803 non-null   int64
dtypes: float64(3), int64(3), object(1)
memory usage: 262.8+ KB

In [11]:
peliculas = peliculas.dropna()

In [12]:
peliculas.isnull().sum()

budget          0
popularity      0
revenue         0
runtime         0
status          0
vote_average    0
vote_count      0
dtype: int64

In [13]:
peliculas["status"].unique()

array(['Released', 'Post Production', 'Rumored'], dtype=object)

In [14]:
peliculas = pd.get_dummies(peliculas, dtype=int)

In [15]:
peliculas.head()

,budget,popularity,revenue,runtime,vote_average,vote_count,status_Post Production,status_Released,status_Rumored
0,237000000,150.437577,2787965087,162.0,7.2,11800,0,1,0
1,300000000,139.082615,961000000,169.0,6.9,4500,0,1,0
2,245000000,107.376788,880674609,148.0,6.3,4466,0,1,0
3,250000000,112.312950,1084939099,165.0,7.6,9106,0,1,0
4,260000000,43.926995,284139100,132.0,6.1,2124,0,1,0

In [16]:
peliculas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4801 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   budget                  4801 non-null   int64
 1   popularity              4801 non-null   float64
 2   revenue                 4801 non-null   int64
 3   runtime                 4801 non-null   float64
 4   vote_average            4801 non-null   float64
 5   vote_count              4801 non-null   int64
 6   status_Post Production  4801 non-null   int64
 7   status_Released         4801 non-null   int64
 8   status_Rumored          4801 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 375.1 KB

In [17]:
peliculas["vote_average"] = peliculas["vote_average"].astype(int)

In [18]:
peliculas.corr()["vote_average"].abs().sort_values(ascending=False)[1:]

runtime                   0.366212
vote_count                0.310369
popularity                0.271287
revenue                   0.194408
budget                    0.086857
status_Released           0.018039
status_Post Production    0.013651
status_Rumored            0.012235
Name: vote_average, dtype: float64

In [19]:
X = peliculas.drop(columns=["vote_average"])
y = peliculas['vote_average']

In [20]:
# Separo X train de X test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

X_train.shape, X_test.shape

((3840, 8), (961, 8))

In [21]:
# Escalo los datos con StandardScaler.

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [22]:
svm_lineal = SVC(kernel="linear", C=1.0, random_state=42)
svm_lineal.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

In [ ]:
svm_poly = SVC(kernel="poly", C=1.0, gamma=10.0, degree=3, random_state=42)
svm_poly.fit(X_train_scaled, y_train)

In [ ]:
svm_rbf = SVC(kernel="rbf", C=1.0, gamma=3.0, random_state=42)
svm_rbf.fit(X_train_scaled, y_train)

NameError: name 'SVC' is not defined

In [ ]:
pred_lineal = svm_lineal.predict(X_test_scaled)
pred_poly = svm_poly.predict(X_test_scaled)
pred_rbf = svm_rbf.predict(X_test_scaled)


print("=== SVM LINEAL ===")
print("Accuracy:", accuracy_score(y_test, pred_lineal)) #exactitud
#print(confusion_matrix(y_test, pred_lineal))
#print(classification_report(y_test, pred_lineal))

print("\n=== SVM POLY ===")
print("Accuracy:", accuracy_score(y_test, pred_poly))
#print(confusion_matrix(y_test, pred_poly))
#print(classification_report(y_test, pred_poly))

print("\n=== SVM RBF ===")
print("Accuracy:", accuracy_score(y_test, pred_rbf))
#print(confusion_matrix(y_test, pred_rbf))
#print(classification_report(y_test, pred_rbf))

In [ ]:
tree_reg = DecisionTreeRegressor(max_depth=15, min_samples_split=200, min_samples_leaf=100,random_state=42)
tree_reg.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=15, min_samples_leaf=100, min_samples_split=200,
                      random_state=42)

In [ ]:
y_pred = tree_reg.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.33610750301016346

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=1000, n_jobs=-1,random_state=42,bootstrap=False)
rnd_clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=False, n_estimators=1000, n_jobs=-1,
                       random_state=42)

In [ ]:
y_pred = rnd_clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.45      0.36      0.40       159
           1       0.79      0.89      0.84       442
           2       0.78      0.71      0.75       284

    accuracy                           0.74       885
   macro avg       0.68      0.66      0.66       885
weighted avg       0.73      0.74      0.73       885

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7401129943502824

Para hacer una pelicula, me basaría principalmente en la popularidad, además del numero de votos al conjunto que la media de votos.
También me fijaría en no pasarme ni quedarme corta de tiempo (duración) de pelicula, normalmente no gusta una pelicula muy larga ni muy corta.

<div style="border-style:groove;border-width:thin;padding:10px">
    <h3>EJERCICIO 2:</h3>
</div>

In [ ]:
estudiantes = pd.read_csv("estudiantes.csv")

estudiantes.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8%,1.4%,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9%,-0.3%,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8%,1.4%,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4%,-0.8%,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9%,-0.3%,0.79,Graduate

In [ ]:
estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             1327 non-null   float64
 11  Father's occupation                             1327 non-null   float64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4424 non-null   object
 20  International                                   4424 non-null   int64
 21  Curricular units 1st sem (credited)             4424 non-null   int64
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4424 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4424 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   object
 34  Inflation rate                                  4424 non-null   object
 35  GDP                                             4424 non-null   float64
 36  Target                                          4424 non-null   object
dtypes: float64(7), int64(26), object(4)
memory usage: 1.2+ MB

In [ ]:
estudiantes[["Age at enrollment", "Unemployment rate", "Inflation rate", "Target"]]

     Age at enrollment Unemployment rate Inflation rate    Target
0               twenty             10.8%           1.4%   Dropout
1             nineteen             13.9%          -0.3%  Graduate
2             nineteen             10.8%           1.4%   Dropout
3               twenty              9.4%          -0.8%  Graduate
4           forty-five             13.9%          -0.3%  Graduate
...                ...               ...            ...       ...
4419          nineteen             15.5%           2.8%  Graduate
4420          eighteen             11.1%           0.6%   Dropout
4421            thirty             13.9%          -0.3%   Dropout
4422            twenty              9.4%          -0.8%  Graduate
4423        twenty-two             12.7%           3.7%  Graduate

[4424 rows x 4 columns]

In [ ]:
estudiantes["Age at enrollment"].unique()

array(['twenty', 'nineteen', 'forty-five', 'fifty', 'eighteen',
       'twenty-two', 'twenty-one', 'thirty-four', 'thirty-seven',
       'forty-three', 'fifty-five', 'thirty-nine', 'twenty-nine',
       'twenty-four', 'twenty-seven', 'twenty-three', 'twenty-six',
       'thirty-three', 'thirty-five', 'twenty-five', 'forty-four',
       'thirty-six', 'forty-seven', 'twenty-eight', 'thirty-eight',
       'thirty', 'thirty-one', 'thirty-two', 'forty', 'forty-two',
       'forty-eight', 'forty-nine', 'forty-six', 'forty-one', 'seventy',
       'sixty', 'fifty-three', 'fifty-one', 'fifty-two', 'fifty-four',
       'sixty-one', 'fifty-eight', 'fifty-nine', '17', 'fifty-seven',
       'sixty-two'], dtype=object)

In [ ]:
estudiantes = estudiantes.drop(columns="Age at enrollment")

In [ ]:
#estudiantes[["Age at enrollment", "Unemployment rate", "Inflation rate", "Target"]]

In [ ]:
Unemployment_rate = []
Inflation_rate = []

for row in estudiantes.iterrows():
    Unemployment_rate = estudiantes["Unemployment rate"].str.replace("%", "").astype(float)
    Inflation_rate = estudiantes["Inflation rate"].str.replace("%", "").astype(float) 

estudiantes['Unemployment rate'] = Unemployment_rate
estudiantes['Inflation rate'] = Inflation_rate

estudiantes.head()

In [ ]:
estudiantes.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [ ]:
estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 36 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             1327 non-null   float64
 11  Father's occupation                             1327 non-null   float64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  International                                   4424 non-null   int64
 20  Curricular units 1st sem (credited)             4424 non-null   int64
 21  Curricular units 1st sem (enrolled)             4424 non-null   int64
 22  Curricular units 1st sem (evaluations)          4424 non-null   int64
 23  Curricular units 1st sem (approved)             4424 non-null   int64
 24  Curricular units 1st sem (grade)                4424 non-null   float64
 25  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 26  Curricular units 2nd sem (credited)             4424 non-null   int64
 27  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 28  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 29  Curricular units 2nd sem (approved)             4424 non-null   int64
 30  Curricular units 2nd sem (grade)                4424 non-null   float64
 31  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 32  Unemployment rate                               4424 non-null   float64
 33  Inflation rate                                  4424 non-null   float64
 34  GDP                                             4424 non-null   float64
 35  Target                                          4424 non-null   object
dtypes: float64(9), int64(26), object(1)
memory usage: 1.2+ MB

In [ ]:
estudiantes.isnull().sum()

Marital status                                       0
Application mode                                     0
Application order                                    0
Course                                               0
Daytime/evening attendance\t                         0
Previous qualification                               0
Previous qualification (grade)                       0
Nacionality                                          0
Mother's qualification                               0
Father's qualification                               0
Mother's occupation                               3097
Father's occupation                               3097
Admission grade                                      0
Displaced                                            0
Educational special needs                            0
Debtor                                               0
Tuition fees up to date                              0
Gender                                               0
Scholarship holder                                   0
International                                        0
Curricular units 1st sem (credited)                  0
Curricular units 1st sem (enrolled)                  0
Curricular units 1st sem (evaluations)               0
Curricular units 1st sem (approved)                  0
Curricular units 1st sem (grade)                     0
Curricular units 1st sem (without evaluations)       0
Curricular units 2nd sem (credited)                  0
Curricular units 2nd sem (enrolled)                  0
Curricular units 2nd sem (evaluations)               0
Curricular units 2nd sem (approved)                  0
Curricular units 2nd sem (grade)                     0
Curricular units 2nd sem (without evaluations)       0
Unemployment rate                                    0
Inflation rate                                       0
GDP                                                  0
Target                                               0
dtype: int64

In [ ]:
estudiantes.shape

(4424, 34)

In [ ]:
estudiantes["Mother\'s occupation"].unique()

array([ nan,   9.,   4.,   5.,   1., 125.,   0.,   3.,   2.,   7.,   6.,
         8., 141.,  90., 191., 194., 143., 132.,  99., 171., 153., 144.,
       193., 152., 122.])

In [ ]:
# Elimino las columnas indicadas abajo ya que tienen muchisimos numeros nulos, eliminar los nulos, nos quedariamos con muy pocos y reemplazarlo por otro valor, romperiamos el modelo, le inventariamos nosotros.
estudiantes = estudiantes.drop(columns=["Mother's occupation", "Father's occupation"])

In [ ]:
estudiantes.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [ ]:
estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 34 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Admission grade                                 4424 non-null   float64
 11  Displaced                                       4424 non-null   int64
 12  Educational special needs                       4424 non-null   int64
 13  Debtor                                          4424 non-null   int64
 14  Tuition fees up to date                         4424 non-null   int64
 15  Gender                                          4424 non-null   int64
 16  Scholarship holder                              4424 non-null   int64
 17  International                                   4424 non-null   int64
 18  Curricular units 1st sem (credited)             4424 non-null   int64
 19  Curricular units 1st sem (enrolled)             4424 non-null   int64
 20  Curricular units 1st sem (evaluations)          4424 non-null   int64
 21  Curricular units 1st sem (approved)             4424 non-null   int64
 22  Curricular units 1st sem (grade)                4424 non-null   float64
 23  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 24  Curricular units 2nd sem (credited)             4424 non-null   int64
 25  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 26  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 27  Curricular units 2nd sem (approved)             4424 non-null   int64
 28  Curricular units 2nd sem (grade)                4424 non-null   float64
 29  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 30  Unemployment rate                               4424 non-null   float64
 31  Inflation rate                                  4424 non-null   float64
 32  GDP                                             4424 non-null   float64
 33  Target                                          4424 non-null   object
dtypes: float64(7), int64(26), object(1)
memory usage: 1.1+ MB

In [ ]:
estudiantes["Target"].unique()

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

In [ ]:
estudiantes["Target"] = estudiantes["Target"].replace({
    "Dropout": 2,
    "Graduate": 1,
    "Enrolled": 0
}).astype(int)

/tmp/ipykernel_20551/1011450246.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  estudiantes["Target"] = estudiantes["Target"].replace({

In [ ]:
estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 34 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Admission grade                                 4424 non-null   float64
 11  Displaced                                       4424 non-null   int64
 12  Educational special needs                       4424 non-null   int64
 13  Debtor                                          4424 non-null   int64
 14  Tuition fees up to date                         4424 non-null   int64
 15  Gender                                          4424 non-null   int64
 16  Scholarship holder                              4424 non-null   int64
 17  International                                   4424 non-null   int64
 18  Curricular units 1st sem (credited)             4424 non-null   int64
 19  Curricular units 1st sem (enrolled)             4424 non-null   int64
 20  Curricular units 1st sem (evaluations)          4424 non-null   int64
 21  Curricular units 1st sem (approved)             4424 non-null   int64
 22  Curricular units 1st sem (grade)                4424 non-null   float64
 23  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 24  Curricular units 2nd sem (credited)             4424 non-null   int64
 25  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 26  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 27  Curricular units 2nd sem (approved)             4424 non-null   int64
 28  Curricular units 2nd sem (grade)                4424 non-null   float64
 29  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 30  Unemployment rate                               4424 non-null   float64
 31  Inflation rate                                  4424 non-null   float64
 32  GDP                                             4424 non-null   float64
 33  Target                                          4424 non-null   int64
dtypes: float64(7), int64(27)
memory usage: 1.1 MB

In [ ]:
estudiantes.corr()["Target"].abs().sort_values(ascending=False)[1:]

Curricular units 2nd sem (grade)                  0.429214
Curricular units 2nd sem (approved)               0.351135
Curricular units 1st sem (grade)                  0.349652
Tuition fees up to date                           0.342121
Curricular units 1st sem (approved)               0.290243
Curricular units 2nd sem (evaluations)            0.194412
Debtor                                            0.154802
Curricular units 1st sem (evaluations)            0.125278
Gender                                            0.118454
Application mode                                  0.116928
Scholarship holder                                0.114517
Mother's qualification                            0.075941
Marital status                                    0.074310
Displaced                                         0.070649
Daytime/evening attendance\t                      0.066439
Curricular units 2nd sem (enrolled)               0.060670
Curricular units 1st sem (enrolled)               0.052020
Curricular units 2nd sem (without evaluations)    0.040991
Admission grade                                   0.038716
Unemployment rate                                 0.037279
GDP                                               0.037052
Father's qualification                            0.035183
Previous qualification                            0.027984
Application order                                 0.027393
Previous qualification (grade)                    0.025096
Course                                            0.024210
Inflation rate                                    0.021798
Curricular units 1st sem (without evaluations)    0.021565
International                                     0.015893
Educational special needs                         0.003751
Curricular units 1st sem (credited)               0.002464
Curricular units 2nd sem (credited)               0.002427
Nacionality                                       0.002098
Name: Target, dtype: float64

In [ ]:
X = estudiantes.drop(columns=["Target"])
y = estudiantes['Target']

In [ ]:
# Separo X train de X test

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((3539, 33), (885, 33))

In [ ]:
# Escalo los datos con StandardScaler.

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
svm_lineal = SVC(kernel="linear", C=1.0, random_state=42)
svm_lineal.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

In [ ]:
svm_poly = SVC(kernel="poly", C=1.0, gamma=1.0, degree=3, random_state=42)
svm_poly.fit(X_train_scaled, y_train)

SVC(gamma=1.0, kernel='poly', random_state=42)

In [ ]:
svm_rbf = SVC(kernel="rbf", C=1.0, gamma=3.0, random_state=42)
svm_rbf.fit(X_train_scaled, y_train)

SVC(gamma=3.0, random_state=42)

In [ ]:
pred_lineal = svm_lineal.predict(X_test_scaled)
pred_poly = svm_poly.predict(X_test_scaled)
pred_rbf = svm_rbf.predict(X_test_scaled)


print("=== SVM LINEAL ===")
print("Accuracy:", accuracy_score(y_test, pred_lineal)) #exactitud
#print(confusion_matrix(y_test, pred_lineal))
#print(classification_report(y_test, pred_lineal))

print("\n=== SVM POLY ===")
print("Accuracy:", accuracy_score(y_test, pred_poly))
#print(confusion_matrix(y_test, pred_poly))
#print(classification_report(y_test, pred_poly))

print("\n=== SVM RBF ===")
print("Accuracy:", accuracy_score(y_test, pred_rbf))
#print(confusion_matrix(y_test, pred_rbf))
#print(classification_report(y_test, pred_rbf))

=== SVM LINEAL ===
Accuracy: 0.7627118644067796

=== SVM POLY ===
Accuracy: 0.6621468926553672

=== SVM RBF ===
Accuracy: 0.4994350282485876

In [ ]:
tree_reg = DecisionTreeRegressor(max_depth=15, min_samples_split=200, min_samples_leaf=100,random_state=42)
tree_reg.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=15, min_samples_leaf=100, min_samples_split=200,
                      random_state=42)

In [ ]:
y_pred = tree_reg.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.2906550680085196

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=1000, n_jobs=-1,random_state=42,bootstrap=False)
rnd_clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=False, n_estimators=1000, n_jobs=-1,
                       random_state=42)

In [ ]:
y_pred = rnd_clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.59      0.38      0.46       159
           1       0.81      0.93      0.87       442
           2       0.83      0.79      0.81       284

    accuracy                           0.79       885
   macro avg       0.74      0.70      0.71       885
weighted avg       0.78      0.79      0.78       885

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7898305084745763

In [ ]:
# PUNTO 6 .

#Eliminaria y voy a eliminar las que menos sentido y correlacion tengan con la columna target.

estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 34 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Admission grade                                 4424 non-null   float64
 11  Displaced                                       4424 non-null   int64
 12  Educational special needs                       4424 non-null   int64
 13  Debtor                                          4424 non-null   int64
 14  Tuition fees up to date                         4424 non-null   int64
 15  Gender                                          4424 non-null   int64
 16  Scholarship holder                              4424 non-null   int64
 17  International                                   4424 non-null   int64
 18  Curricular units 1st sem (credited)             4424 non-null   int64
 19  Curricular units 1st sem (enrolled)             4424 non-null   int64
 20  Curricular units 1st sem (evaluations)          4424 non-null   int64
 21  Curricular units 1st sem (approved)             4424 non-null   int64
 22  Curricular units 1st sem (grade)                4424 non-null   float64
 23  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 24  Curricular units 2nd sem (credited)             4424 non-null   int64
 25  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 26  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 27  Curricular units 2nd sem (approved)             4424 non-null   int64
 28  Curricular units 2nd sem (grade)                4424 non-null   float64
 29  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 30  Unemployment rate                               4424 non-null   float64
 31  Inflation rate                                  4424 non-null   float64
 32  GDP                                             4424 non-null   float64
 33  Target                                          4424 non-null   int64
dtypes: float64(7), int64(27)
memory usage: 1.1 MB

In [ ]:
estudiantes.corr()["Target"].abs().sort_values(ascending=True)[1:]

Curricular units 2nd sem (credited)               0.002427
Curricular units 1st sem (credited)               0.002464
Educational special needs                         0.003751
International                                     0.015893
Curricular units 1st sem (without evaluations)    0.021565
Inflation rate                                    0.021798
Course                                            0.024210
Previous qualification (grade)                    0.025096
Application order                                 0.027393
Previous qualification                            0.027984
Father's qualification                            0.035183
GDP                                               0.037052
Unemployment rate                                 0.037279
Admission grade                                   0.038716
Curricular units 2nd sem (without evaluations)    0.040991
Curricular units 1st sem (enrolled)               0.052020
Curricular units 2nd sem (enrolled)               0.060670
Daytime/evening attendance\t                      0.066439
Displaced                                         0.070649
Marital status                                    0.074310
Mother's qualification                            0.075941
Scholarship holder                                0.114517
Application mode                                  0.116928
Gender                                            0.118454
Curricular units 1st sem (evaluations)            0.125278
Debtor                                            0.154802
Curricular units 2nd sem (evaluations)            0.194412
Curricular units 1st sem (approved)               0.290243
Tuition fees up to date                           0.342121
Curricular units 1st sem (grade)                  0.349652
Curricular units 2nd sem (approved)               0.351135
Curricular units 2nd sem (grade)                  0.429214
Target                                            1.000000
Name: Target, dtype: float64

In [ ]:
estudiantes_nuevo = estudiantes.drop(columns=["Curricular units 2nd sem (credited)", "Curricular units 1st sem (credited)", "Educational special needs", "International", "Curricular units 1st sem (without evaluations)",  "Inflation rate", 
                                              "Course", "Previous qualification (grade)", "Application order", "Previous qualification", "Father's qualification", "GDP", "Unemployment rate",
                                               "Admission grade",  "Curricular units 2nd sem (without evaluations)", "Curricular units 1st sem (enrolled)", "Curricular units 1st sem (enrolled)",
                                               "Curricular units 2nd sem (enrolled)", "Daytime/evening attendance\t", "Displaced"])

In [ ]:
X = estudiantes_nuevo.drop(columns=["Target"])
y = estudiantes_nuevo['Target']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((3539, 14), (885, 14))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=1000, n_jobs=-1,random_state=42,bootstrap=False)
rnd_clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=False, n_estimators=1000, n_jobs=-1,
                       random_state=42)

In [ ]:
y_pred = rnd_clf.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.45      0.35      0.39       159
           1       0.79      0.89      0.84       442
           2       0.79      0.72      0.75       284

    accuracy                           0.74       885
   macro avg       0.67      0.66      0.66       885
weighted avg       0.73      0.74      0.73       885

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7344632768361582