In [1]:
import pandas as pd
#1.1 - Importa el csv adjunto con el examen, de nombre "marketing_campaign.csv",en un Dataframe.
#Debes usar el parametro sep ='\t' porque no usa; sino tabulaciones para separar los datos.

#df_nba = pd.read_csv("nba.csv")
df_marketing = pd.read_csv("marketing_campaign.csv",sep='\t')

In [ ]:
#1.2 -Cambia la columna dt_customer a formato Datetime y quedate con los 1000 clientes mas modernos.
# El cambio debe de ser permanente y usarlo a partir de aqui en todo el examen, salvo que se indique lo contrario 

import datetime as dt
import pandas as pd

df_marketing["Dt_Customer"] = pd.to_datetime(df_marketing["Dt_Customer"],dayfirst=True)
df_marketing.head()
    
df_filtrado_marketing = df_marketing.sort_values("Dt_Customer", ascending=False, inplace=False).head(1000)

df_filtrado_marketing.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
200,7300,1952,Graduation,Divorced,69142,0,1,2014-06-29,50,448,...,5,0,1,0,0,0,0,3,11,0
989,453,1956,PhD,Widow,35340,1,1,2014-06-29,1,27,...,5,0,0,0,0,0,0,3,11,0
1812,8093,1969,Master,Married,79734,0,0,2014-06-28,72,572,...,1,0,0,0,1,0,0,3,11,0
796,6722,1954,PhD,Married,70421,0,1,2014-06-28,98,479,...,6,0,0,0,0,0,0,3,11,0
45,1371,1976,Graduation,Single,79941,0,0,2014-06-28,72,123,...,1,0,0,0,0,0,0,3,11,0

In [ ]:
# 1.3 Recorrer dataframe para generar una columna nueva llamada "Probably_Died". El valor de esta columna será True en los casos que el cliente
#haya nacido hace mas de 100 años.False en el resto de casos.Recuerda hacerlo recorriendo el dataframe.


fecha = 1925
datas = []
probabilidad = []


for dfs in datas:
    if fecha > df_filtrado_marketing['Year_Birth']:
    probabilidad.append(df_filtrado_marketing["Probably_Died"])
    df_actualizado = pd.DataFrame({"Probably_Died": probabilidad})


df_actualizado = pd.DataFrame({"Probably_Died": probabilidad})

IndentationError: expected an indented block after 'if' statement on line 10 (4267707764.py, line 11)

In [ ]:
# 1.4 Crea una funcion (llamada new_column)que reciba un dataframe y devuelva un pandas series con lasuma de las columnas MntWInes y MntFruits
import numpy as np
sum = []
def new_column(df):
    sum = df_filtrado_marketing["MntWines"] + df_filtrado_marketing["MntFruits"]
    sum.append(df_filtrado_marketing["Suma_wines_fruits"])
    return sum

#print(df_filtrado_marketing)
df_filtrado_marketing.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
200,7300,1952,Graduation,Divorced,69142,0,1,2014-06-29,50,448,...,5,0,1,0,0,0,0,3,11,0
989,453,1956,PhD,Widow,35340,1,1,2014-06-29,1,27,...,5,0,0,0,0,0,0,3,11,0
1812,8093,1969,Master,Married,79734,0,0,2014-06-28,72,572,...,1,0,0,0,1,0,0,3,11,0
796,6722,1954,PhD,Married,70421,0,1,2014-06-28,98,479,...,6,0,0,0,0,0,0,3,11,0
45,1371,1976,Graduation,Single,79941,0,0,2014-06-28,72,123,...,1,0,0,0,0,0,0,3,11,0

In [ ]:
#1.5 convierte la columna education para que sea numerica. df_filtrado_marketing['Education'].unique(). que te devolvera todos
#los valores unicos

df_filtrado_marketing['Education'].unique()


def limpiados(n):
    if type(n) == int:
        for row in df_filtrado_marketing.iterrows():
            educacion = df_filtrado_marketing["Education"].str.replace("Graduation", "1").str.replace("PhD", "3").str.replace("2n Cycle", "4").str.replace("Basic", "5").astype(int)
    
        df_limpio = pd.DataFrame({"Education": educacion})
        return df_limpio
        print(df_limpio)
    df_limpio.head()

In [ ]:
#1.6

#var1 = 400
#var2 = 80000
#if 
#df_filtrado_marketing["MntWines"] > var1
#sum.append(df_filtrado_marketing["Suma_wines_fruits"])
VIP_clients = df_filtrado_marketing["MntWines"] > 400 and ["Income"] > 80000

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().