Rúbrica: 

A continuación se muestra la rúbrica con la que se va a corregir el examen:


| Apartado/Criterio | Ponderación | Nota |
| :-- | --- | --- |
| Ej. 1.1. Ha tratado de manera adecuada los datos de las columnas. | 1 | 1 |
| Ej. 1.1. Ha seguido un criterio adecuado para elegir las entradas del problema. | 1 | 1 |
| Ej. 1.2. Ha diseñado bien la red y el sistema de entrenamiento | 1 | 0,75 |
| Ej. 1.2. Ha dimensionado bien la red neuronal. | 1 | 1 |
| Ej. 1.2. Ha hecho modificaciones coherentes para conseguir un mejor resultado. | 0,5 | 0,3 |
| Ej. 1.2. Ha usado su experiencia para valorar si el resultado es válido o no. | 1 | 0 |
| Ej. 2.1. Ha cargado adecuadamente los datos. | 0,5 | 0,5 |
| Ej. 2.2. Ha diseñado bien la red y el sistema de entrenamiento | 1 | 0,75 |
| Ej. 2.2. Ha dimensionado bien la red neuronal. | 1 | 0,5 |
| Ej. 2.2. Ha hecho modificaciones coherentes para conseguir un mejor resultado. | 1 | 1 |
| Ej. 2.2. Ha usado su experiencia para valorar si el resultado es válido o no. | 1 | 0 |

TOTAL: 6,8

In [896]:
from os import listdir
from numpy import asarray
from numpy import save
import tensorflow as tf
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from tensorflow import keras
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVR
from sklearn.metrics import classification_report
import datetime
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import os

In [897]:
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

## Ejercicio 1

In [898]:
vuelos = pd.read_csv("/home/ciabd03/Descargas/vuelos_pakistan.csv")

vuelos.head()

,Flight_ID,Date,Month,Day_of_Week,Departure_City,Arrival_City,Route_Type,Aircraft_Type,Flight_Duration_Minutes,Passengers,...,Load_Factor_%,Ticket_Price_USD,Delay_Minutes,Delay_Category,On_Time_Status,Weather_Condition,Fuel_Consumption,CO2_Emissions,Customer_Rating,Customer_Feedback
0,PK2026_0001,2026-06-09,June,Tuesday,Jeddah,Islamabad,International,Airbus A320,83.0,120,...,66.67,1140.0,220,Severe,Delayed,Clear,6265l,15662.5kg,4.1,Dreadful customer support
1,PK2026_0002,2026-08-12,August,Wednesday,Dubai,Kuala Lumpur,International,Airbus A320,284.0,179,...,99.44,773.0,27,Minor,Delayed,NaN,3516l,8790.0kg,3.6,"Standard flight, nothing special"
2,PK2026_0003,2026-04-20,April,Monday,Doha,Lahore,International,ATR 72,333.0,69,...,98.57,155.0,176,Severe,Delayed,Fog,13538l,33845.0kg,3.0,Tardy arrival but very cozy
3,PK2026_0004,2026-12-07,December,Monday,Jeddah,Lahore,International,Boeing 777,330.0,291,...,83.14,1237.0,87,Moderate,Delayed,NaN,18850l,47125.0kg,NaN,Mediocre experience overall
4,PK2026_0005,2026-05-04,May,Monday,Lahore,Doha,International,Boeing 737,283.0,159,...,99.38,141.0,82,Moderate,Delayed,NaN,13474l,33685.0kg,3.0,Behind schedule but quite relaxed

In [899]:
vuelos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                800 non-null    object
 1   Date                     800 non-null    object
 2   Month                    800 non-null    object
 3   Day_of_Week              800 non-null    object
 4   Departure_City           800 non-null    object
 5   Arrival_City             800 non-null    object
 6   Route_Type               800 non-null    object
 7   Aircraft_Type            800 non-null    object
 8   Flight_Duration_Minutes  725 non-null    float64
 9   Passengers               800 non-null    int64
 10  Seat_Capacity            800 non-null    int64
 11  Load_Factor_%            800 non-null    float64
 12  Ticket_Price_USD         786 non-null    float64
 13  Delay_Minutes            800 non-null    int64
 14  Delay_Category           800 non-null    object
 15  On_Time_Status           800 non-null    object
 16  Weather_Condition        521 non-null    object
 17  Fuel_Consumption         800 non-null    object
 18  CO2_Emissions            800 non-null    object
 19  Customer_Rating          673 non-null    float64
 20  Customer_Feedback        800 non-null    object
dtypes: float64(4), int64(3), object(14)
memory usage: 131.4+ KB

In [900]:
vuelos = vuelos.drop(["Weather_Condition"],axis=1)

In [901]:
vuelos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                800 non-null    object
 1   Date                     800 non-null    object
 2   Month                    800 non-null    object
 3   Day_of_Week              800 non-null    object
 4   Departure_City           800 non-null    object
 5   Arrival_City             800 non-null    object
 6   Route_Type               800 non-null    object
 7   Aircraft_Type            800 non-null    object
 8   Flight_Duration_Minutes  725 non-null    float64
 9   Passengers               800 non-null    int64
 10  Seat_Capacity            800 non-null    int64
 11  Load_Factor_%            800 non-null    float64
 12  Ticket_Price_USD         786 non-null    float64
 13  Delay_Minutes            800 non-null    int64
 14  Delay_Category           800 non-null    object
 15  On_Time_Status           800 non-null    object
 16  Fuel_Consumption         800 non-null    object
 17  CO2_Emissions            800 non-null    object
 18  Customer_Rating          673 non-null    float64
 19  Customer_Feedback        800 non-null    object
dtypes: float64(4), int64(3), object(13)
memory usage: 125.1+ KB

In [902]:
vuelos["Flight_Duration_Minutes"].fillna(vuelos["Flight_Duration_Minutes"].median(),inplace=True)

/tmp/ipykernel_25307/2744780676.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  vuelos["Flight_Duration_Minutes"].fillna(vuelos["Flight_Duration_Minutes"].median(),inplace=True)

In [903]:
vuelos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                800 non-null    object
 1   Date                     800 non-null    object
 2   Month                    800 non-null    object
 3   Day_of_Week              800 non-null    object
 4   Departure_City           800 non-null    object
 5   Arrival_City             800 non-null    object
 6   Route_Type               800 non-null    object
 7   Aircraft_Type            800 non-null    object
 8   Flight_Duration_Minutes  800 non-null    float64
 9   Passengers               800 non-null    int64
 10  Seat_Capacity            800 non-null    int64
 11  Load_Factor_%            800 non-null    float64
 12  Ticket_Price_USD         786 non-null    float64
 13  Delay_Minutes            800 non-null    int64
 14  Delay_Category           800 non-null    object
 15  On_Time_Status           800 non-null    object
 16  Fuel_Consumption         800 non-null    object
 17  CO2_Emissions            800 non-null    object
 18  Customer_Rating          673 non-null    float64
 19  Customer_Feedback        800 non-null    object
dtypes: float64(4), int64(3), object(13)
memory usage: 125.1+ KB

In [ ]:
vuelos["Ticket_Price_USD"].fillna(vuelos["Ticket_Price_USD"].median(),inplace=True)
#CORRECCIÓN: El fillna con la columna objetivo no es buena idea por su relevancia. Nos estamos inventando resultados.

/tmp/ipykernel_25307/2753229801.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  vuelos["Ticket_Price_USD"].fillna(vuelos["Ticket_Price_USD"].median(),inplace=True)

In [905]:
vuelos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                800 non-null    object
 1   Date                     800 non-null    object
 2   Month                    800 non-null    object
 3   Day_of_Week              800 non-null    object
 4   Departure_City           800 non-null    object
 5   Arrival_City             800 non-null    object
 6   Route_Type               800 non-null    object
 7   Aircraft_Type            800 non-null    object
 8   Flight_Duration_Minutes  800 non-null    float64
 9   Passengers               800 non-null    int64
 10  Seat_Capacity            800 non-null    int64
 11  Load_Factor_%            800 non-null    float64
 12  Ticket_Price_USD         800 non-null    float64
 13  Delay_Minutes            800 non-null    int64
 14  Delay_Category           800 non-null    object
 15  On_Time_Status           800 non-null    object
 16  Fuel_Consumption         800 non-null    object
 17  CO2_Emissions            800 non-null    object
 18  Customer_Rating          673 non-null    float64
 19  Customer_Feedback        800 non-null    object
dtypes: float64(4), int64(3), object(13)
memory usage: 125.1+ KB

In [906]:
vuelos["Customer_Rating"].fillna(vuelos["Customer_Rating"].median(),inplace=True)

/tmp/ipykernel_25307/1084780879.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  vuelos["Customer_Rating"].fillna(vuelos["Customer_Rating"].median(),inplace=True)

In [907]:
vuelos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                800 non-null    object
 1   Date                     800 non-null    object
 2   Month                    800 non-null    object
 3   Day_of_Week              800 non-null    object
 4   Departure_City           800 non-null    object
 5   Arrival_City             800 non-null    object
 6   Route_Type               800 non-null    object
 7   Aircraft_Type            800 non-null    object
 8   Flight_Duration_Minutes  800 non-null    float64
 9   Passengers               800 non-null    int64
 10  Seat_Capacity            800 non-null    int64
 11  Load_Factor_%            800 non-null    float64
 12  Ticket_Price_USD         800 non-null    float64
 13  Delay_Minutes            800 non-null    int64
 14  Delay_Category           800 non-null    object
 15  On_Time_Status           800 non-null    object
 16  Fuel_Consumption         800 non-null    object
 17  CO2_Emissions            800 non-null    object
 18  Customer_Rating          800 non-null    float64
 19  Customer_Feedback        800 non-null    object
dtypes: float64(4), int64(3), object(13)
memory usage: 125.1+ KB

In [908]:
vuelos_clean = vuelos.copy()
vuelos_clean = vuelos_clean.drop(["Flight_ID","Date","Customer_Feedback"],axis=1)

In [909]:
vuelos_clean.head()

,Month,Day_of_Week,Departure_City,Arrival_City,Route_Type,Aircraft_Type,Flight_Duration_Minutes,Passengers,Seat_Capacity,Load_Factor_%,Ticket_Price_USD,Delay_Minutes,Delay_Category,On_Time_Status,Fuel_Consumption,CO2_Emissions,Customer_Rating
0,June,Tuesday,Jeddah,Islamabad,International,Airbus A320,83.0,120,180,66.67,1140.0,220,Severe,Delayed,6265l,15662.5kg,4.1
1,August,Wednesday,Dubai,Kuala Lumpur,International,Airbus A320,284.0,179,180,99.44,773.0,27,Minor,Delayed,3516l,8790.0kg,3.6
2,April,Monday,Doha,Lahore,International,ATR 72,333.0,69,70,98.57,155.0,176,Severe,Delayed,13538l,33845.0kg,3.0
3,December,Monday,Jeddah,Lahore,International,Boeing 777,330.0,291,350,83.14,1237.0,87,Moderate,Delayed,18850l,47125.0kg,3.7
4,May,Monday,Lahore,Doha,International,Boeing 737,283.0,159,160,99.38,141.0,82,Moderate,Delayed,13474l,33685.0kg,3.0

In [ ]:
Mes = []

for i, row in vuelos_clean.iterrows():
    if row["Month"] == "January":
        Mes.append(1)
    if row["Month"] == "February":
        Mes.append(2)
    if row["Month"] == "March":
        Mes.append(3)
    if row["Month"] == "April":
        Mes.append(4)
    if row["Month"] == "May":
        Mes.append(5)
    if row["Month"] == "June":
        Mes.append(6)
    if row["Month"] == "July":
        Mes.append(7)
    if row["Month"] == "August":
        Mes.append(8)
    if row["Month"] == "September":
        Mes.append(9)
    if row["Month"] == "October":
        Mes.append(10)
    if row["Month"] == "November":
        Mes.append(11)
    if row["Month"] == "December":
        Mes.append(12)

vuelos_clean["Month"] = Mes

#CORRECCIÓN: Ojo con el label encoding. En este caso, como en muchos, mete un pequeño sesgo.

In [911]:
vuelos_clean.head()
vuelos_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Month                    800 non-null    int64
 1   Day_of_Week              800 non-null    object
 2   Departure_City           800 non-null    object
 3   Arrival_City             800 non-null    object
 4   Route_Type               800 non-null    object
 5   Aircraft_Type            800 non-null    object
 6   Flight_Duration_Minutes  800 non-null    float64
 7   Passengers               800 non-null    int64
 8   Seat_Capacity            800 non-null    int64
 9   Load_Factor_%            800 non-null    float64
 10  Ticket_Price_USD         800 non-null    float64
 11  Delay_Minutes            800 non-null    int64
 12  Delay_Category           800 non-null    object
 13  On_Time_Status           800 non-null    object
 14  Fuel_Consumption         800 non-null    object
 15  CO2_Emissions            800 non-null    object
 16  Customer_Rating          800 non-null    float64
dtypes: float64(4), int64(4), object(9)
memory usage: 106.4+ KB

In [912]:
Dia = []

for i, row in vuelos_clean.iterrows():
    if row["Day_of_Week"] == "Monday":
        Dia.append(1)
    if row["Day_of_Week"] == "Tuesday":
        Dia.append(2)
    if row["Day_of_Week"] == "Wednesday":
        Dia.append(3)
    if row["Day_of_Week"] == "Thursday":
        Dia.append(4)
    if row["Day_of_Week"] == "Friday":
        Dia.append(5)
    if row["Day_of_Week"] == "Saturday":
        Dia.append(6)
    if row["Day_of_Week"] == "Sunday":
        Dia.append(7)

vuelos_clean["Day_of_Week"] = Dia

In [913]:
vuelos_clean.head()
vuelos_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Month                    800 non-null    int64
 1   Day_of_Week              800 non-null    int64
 2   Departure_City           800 non-null    object
 3   Arrival_City             800 non-null    object
 4   Route_Type               800 non-null    object
 5   Aircraft_Type            800 non-null    object
 6   Flight_Duration_Minutes  800 non-null    float64
 7   Passengers               800 non-null    int64
 8   Seat_Capacity            800 non-null    int64
 9   Load_Factor_%            800 non-null    float64
 10  Ticket_Price_USD         800 non-null    float64
 11  Delay_Minutes            800 non-null    int64
 12  Delay_Category           800 non-null    object
 13  On_Time_Status           800 non-null    object
 14  Fuel_Consumption         800 non-null    object
 15  CO2_Emissions            800 non-null    object
 16  Customer_Rating          800 non-null    float64
dtypes: float64(4), int64(5), object(8)
memory usage: 106.4+ KB

In [914]:
vuelos_clean.head()

,Month,Day_of_Week,Departure_City,Arrival_City,Route_Type,Aircraft_Type,Flight_Duration_Minutes,Passengers,Seat_Capacity,Load_Factor_%,Ticket_Price_USD,Delay_Minutes,Delay_Category,On_Time_Status,Fuel_Consumption,CO2_Emissions,Customer_Rating
0,6,2,Jeddah,Islamabad,International,Airbus A320,83.0,120,180,66.67,1140.0,220,Severe,Delayed,6265l,15662.5kg,4.1
1,8,3,Dubai,Kuala Lumpur,International,Airbus A320,284.0,179,180,99.44,773.0,27,Minor,Delayed,3516l,8790.0kg,3.6
2,4,1,Doha,Lahore,International,ATR 72,333.0,69,70,98.57,155.0,176,Severe,Delayed,13538l,33845.0kg,3.0
3,12,1,Jeddah,Lahore,International,Boeing 777,330.0,291,350,83.14,1237.0,87,Moderate,Delayed,18850l,47125.0kg,3.7
4,5,1,Lahore,Doha,International,Boeing 737,283.0,159,160,99.38,141.0,82,Moderate,Delayed,13474l,33685.0kg,3.0

In [915]:
co2 = []
fuel = []

for i, row in vuelos_clean.iterrows():
    co2.append(float(row["CO2_Emissions"].replace("kg","")))

for i, row in vuelos_clean.iterrows():
    fuel.append(float(row["Fuel_Consumption"].replace("l","")))

vuelos_clean["CO2_Emissions"] = co2
vuelos_clean["Fuel_Consumption"] = fuel

In [916]:
vuelos_clean.head()

,Month,Day_of_Week,Departure_City,Arrival_City,Route_Type,Aircraft_Type,Flight_Duration_Minutes,Passengers,Seat_Capacity,Load_Factor_%,Ticket_Price_USD,Delay_Minutes,Delay_Category,On_Time_Status,Fuel_Consumption,CO2_Emissions,Customer_Rating
0,6,2,Jeddah,Islamabad,International,Airbus A320,83.0,120,180,66.67,1140.0,220,Severe,Delayed,6265.0,15662.5,4.1
1,8,3,Dubai,Kuala Lumpur,International,Airbus A320,284.0,179,180,99.44,773.0,27,Minor,Delayed,3516.0,8790.0,3.6
2,4,1,Doha,Lahore,International,ATR 72,333.0,69,70,98.57,155.0,176,Severe,Delayed,13538.0,33845.0,3.0
3,12,1,Jeddah,Lahore,International,Boeing 777,330.0,291,350,83.14,1237.0,87,Moderate,Delayed,18850.0,47125.0,3.7
4,5,1,Lahore,Doha,International,Boeing 737,283.0,159,160,99.38,141.0,82,Moderate,Delayed,13474.0,33685.0,3.0

In [917]:
vuelos_clean = pd.get_dummies(vuelos_clean,dtype=int)

In [918]:
vuelos_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Month                        800 non-null    int64
 1   Day_of_Week                  800 non-null    int64
 2   Flight_Duration_Minutes      800 non-null    float64
 3   Passengers                   800 non-null    int64
 4   Seat_Capacity                800 non-null    int64
 5   Load_Factor_%                800 non-null    float64
 6   Ticket_Price_USD             800 non-null    float64
 7   Delay_Minutes                800 non-null    int64
 8   Fuel_Consumption             800 non-null    float64
 9   CO2_Emissions                800 non-null    float64
 10  Customer_Rating              800 non-null    float64
 11  Departure_City_Doha          800 non-null    int64
 12  Departure_City_Dubai         800 non-null    int64
 13  Departure_City_Islamabad     800 non-null    int64
 14  Departure_City_Jeddah        800 non-null    int64
 15  Departure_City_Karachi       800 non-null    int64
 16  Departure_City_Kuala Lumpur  800 non-null    int64
 17  Departure_City_Lahore        800 non-null    int64
 18  Departure_City_London        800 non-null    int64
 19  Arrival_City_Doha            800 non-null    int64
 20  Arrival_City_Dubai           800 non-null    int64
 21  Arrival_City_Islamabad       800 non-null    int64
 22  Arrival_City_Jeddah          800 non-null    int64
 23  Arrival_City_Karachi         800 non-null    int64
 24  Arrival_City_Kuala Lumpur    800 non-null    int64
 25  Arrival_City_Lahore          800 non-null    int64
 26  Arrival_City_London          800 non-null    int64
 27  Route_Type_Domestic          800 non-null    int64
 28  Route_Type_International     800 non-null    int64
 29  Aircraft_Type_ATR 72         800 non-null    int64
 30  Aircraft_Type_Airbus A320    800 non-null    int64
 31  Aircraft_Type_Boeing 737     800 non-null    int64
 32  Aircraft_Type_Boeing 777     800 non-null    int64
 33  Delay_Category_Minor         800 non-null    int64
 34  Delay_Category_Moderate      800 non-null    int64
 35  Delay_Category_No Delay      800 non-null    int64
 36  Delay_Category_Severe        800 non-null    int64
 37  On_Time_Status_Delayed       800 non-null    int64
 38  On_Time_Status_On Time       800 non-null    int64
dtypes: float64(6), int64(33)
memory usage: 243.9 KB

In [919]:
vuelos_clean.corr()["Ticket_Price_USD"].abs().sort_values(ascending=False)[1:]

Arrival_City_Jeddah            0.078116
Departure_City_Karachi         0.067351
Month                          0.056245
Departure_City_Lahore          0.055104
Delay_Category_No Delay        0.051729
Departure_City_Dubai           0.045542
Arrival_City_Karachi           0.039336
Departure_City_Kuala Lumpur    0.036338
Delay_Category_Moderate        0.036223
Delay_Minutes                  0.032122
Arrival_City_London            0.030587
Passengers                     0.026216
Delay_Category_Severe          0.024043
Customer_Rating                0.023571
Arrival_City_Dubai             0.021898
On_Time_Status_Delayed         0.021497
On_Time_Status_On Time         0.021497
Aircraft_Type_Airbus A320      0.020245
Route_Type_International       0.019910
Route_Type_Domestic            0.019910
Arrival_City_Islamabad         0.019562
Arrival_City_Lahore            0.018860
CO2_Emissions                  0.018081
Fuel_Consumption               0.018081
Day_of_Week                    0.016370
Aircraft_Type_ATR 72           0.014630
Departure_City_London          0.014471
Seat_Capacity                  0.012348
Aircraft_Type_Boeing 737       0.012102
Arrival_City_Kuala Lumpur      0.011058
Departure_City_Jeddah          0.010460
Departure_City_Doha            0.009350
Delay_Category_Minor           0.007249
Aircraft_Type_Boeing 777       0.006072
Arrival_City_Doha              0.005539
Load_Factor_%                  0.004948
Departure_City_Islamabad       0.003760
Flight_Duration_Minutes        0.001281
Name: Ticket_Price_USD, dtype: float64

In [920]:
X = vuelos_clean.drop(["Ticket_Price_USD"],axis=1)
y = vuelos_clean["Ticket_Price_USD"]

In [921]:
escalador = StandardScaler()
X = escalador.fit_transform(X)
y = escalador.fit_transform(y.to_frame())

In [922]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X,y,test_size=0.1,random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full,y_train_full,test_size=0.1,random_state=42)

In [923]:
X_train.shape[1:]

(38,)

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(24,input_shape=X_train.shape[1:],activation="relu"))
model.add(keras.layers.Dense(5,activation="relu"))
model.add(keras.layers.Dense(1))

#CORRECCIÓN: El diseño de la red está bien (Acorde a regresión) y el dimensionamiento también está bien. Para el entrenamiento
# has puesto un early stopping aunque, con este tipo de ejercicio habría que dejar algo más de paciencia.
#No has hecho nada para valorar si el resultado está bien (un árbol de decisión o un random forest inicial).

/home/ciabd03/anaconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [925]:
""" model = keras.models.Sequential()
model.add(keras.layers.Dense(24,input_shape=X_train.shape[1:],activation="relu"))
model.add(keras.layers.Dense(5,activation="relu"))
model.add(keras.layers.Dense(1, activation="relu")) """

' model = keras.models.Sequential()\nmodel.add(keras.layers.Dense(24,input_shape=X_train.shape[1:],activation="relu"))\nmodel.add(keras.layers.Dense(5,activation="relu"))\nmodel.add(keras.layers.Dense(1, activation="relu")) '

In [926]:
""" model = keras.models.Sequential()
model.add(keras.layers.Dense(30,input_shape=X_train.shape[1:],activation="relu"))
model.add(keras.layers.Dense(15,activation="relu"))
model.add(keras.layers.Dense(1)) """

' model = keras.models.Sequential()\nmodel.add(keras.layers.Dense(30,input_shape=X_train.shape[1:],activation="relu"))\nmodel.add(keras.layers.Dense(15,activation="relu"))\nmodel.add(keras.layers.Dense(1)) '

In [ ]:
""" model = keras.models.Sequential()
model.add(keras.layers.Dense(3,input_shape=X_train.shape[1:],activation="relu"))
model.add(keras.layers.Dense(2,activation="relu"))
model.add(keras.layers.Dense(1)) """
#CORRECCIÓN: Las pruebas que has hecho son coherentes pero tendrías que haber subido también el número de épocas.

' model = keras.models.Sequential()\nmodel.add(keras.layers.Dense(3,input_shape=X_train.shape[1:],activation="relu"))\nmodel.add(keras.layers.Dense(2,activation="relu"))\nmodel.add(keras.layers.Dense(1)) '

In [928]:
model.compile(loss="mean_squared_error", optimizer=keras.optimizers.SGD(learning_rate=0.0005), metrics=["mse"])

In [929]:
early_stopping_cb = keras.callbacks.EarlyStopping(patience=5,restore_best_weights=True)

In [930]:
history = model.fit(X_train,y_train, epochs=1000,validation_data=(X_val,y_val),callbacks=[early_stopping_cb])

Epoch 1/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8989 - mse: 1.8989 - val_loss: 1.6673 - val_mse: 1.6673
Epoch 2/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7022 - mse: 1.7022 - val_loss: 1.5330 - val_mse: 1.5330
Epoch 3/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5581 - mse: 1.5581 - val_loss: 1.4335 - val_mse: 1.4335
Epoch 4/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.4504 - mse: 1.4504 - val_loss: 1.3609 - val_mse: 1.3609
Epoch 5/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.3701 - mse: 1.3701 - val_loss: 1.3065 - val_mse: 1.3065
Epoch 6/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.3091 - mse: 1.3091 - val_loss: 1.2603 - val_mse: 1.2603
Epoch 7/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2569 - mse: 1.2569 - val_loss: 1.2276 - val_mse: 1.2276
Epoch 8/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2183 - mse: 1.2183 - val_loss: 1.1990 - val_mse: 1.1990
Epoch 9/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1846 - mse: 1.1846 - val_loss: 1.1765 - val_mse: 1.1765
Epoch 10/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1573 - mse: 1.1573 - val_loss: 1.1585 - val_mse: 1.1585
Epoch 11/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1356 - mse: 1.1356 - val_loss: 1.1425 - val_mse: 1.1425
Epoch 12/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1169 - mse: 1.1169 - val_loss: 1.1290 - val_mse: 1.1290
Epoch 13/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1009 - mse: 1.1009 - val_loss: 1.1179 - val_mse: 1.1179
Epoch 14/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0885 - mse: 1.0885 - val_loss: 1.1093 - val_mse: 1.1093
Epoch 15/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0777 - mse: 1.0777 - val_loss: 1.1024 - val_mse: 1.1024
Epoch 16/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0686 - mse: 1.0686 - val_loss: 1.0962 - val_mse: 1.0962
Epoch 17/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0604 - mse: 1.0604 - val_loss: 1.0904 - val_mse: 1.0904
Epoch 18/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0530 - mse: 1.0530 - val_loss: 1.0861 - val_mse: 1.0861
Epoch 19/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0464 - mse: 1.0464 - val_loss: 1.0825 - val_mse: 1.0825
Epoch 20/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0408 - mse: 1.0408 - val_loss: 1.0792 - val_mse: 1.0792
Epoch 21/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0359 - mse: 1.0359 - val_loss: 1.0762 - val_mse: 1.0762
Epoch 22/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0316 - mse: 1.0316 - val_loss: 1.0735 - val_mse: 1.0735
Epoch 23/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0271 - mse: 1.0271 - val_loss: 1.0713 - val_mse: 1.0713
Epoch 24/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0234 - mse: 1.0234 - val_loss: 1.0690 - val_mse: 1.0690
Epoch 25/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0201 - mse: 1.0201 - val_loss: 1.0672 - val_mse: 1.0672
Epoch 26/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0170 - mse: 1.0170 - val_loss: 1.0662 - val_mse: 1.0662
Epoch 27/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0145 - mse: 1.0145 - val_loss: 1.0651 - val_mse: 1.0651
Epoch 28/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0121 - mse: 1.0121 - val_loss: 1.0639 - val_mse: 1.0639
Epoch 29/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0099 - mse: 1.0099 - val_loss: 1.0626 - val_mse: 1.0626
Epoch 30/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0077 - mse: 1.0077 - val_loss: 1.0613 - val_mse: 1.0613
Epoch 31/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0053 - mse: 1.0053 - val_loss: 1.0606 - val_mse: 1.0606
Epoch 32/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0033 - mse: 1.0033 - val_loss: 1.0597 - val_mse: 1.0597
Epoch 33/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0014 - mse: 1.0014 - val_loss: 1.0591 - val_mse: 1.0591
Epoch 34/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9995 - mse: 0.9995 - val_loss: 1.0584 - val_mse: 1.0584
Epoch 35/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9976 - mse: 0.9976 - val_loss: 1.0576 - val_mse: 1.0576
Epoch 36/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9960 - mse: 0.9960 - val_loss: 1.0568 - val_mse: 1.0568
Epoch 37/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9940 - mse: 0.9940 - val_loss: 1.0561 - val_mse: 1.0561
Epoch 38/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9926 - mse: 0.9926 - val_loss: 1.0553 - val_mse: 1.0553
Epoch 39/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9911 - mse: 0.9911 - val_loss: 1.0545 - val_mse: 1.0545
Epoch 40/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9896 - mse: 0.9896 - val_loss: 1.0539 - val_mse: 1.0539
Epoch 41/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9881 - mse: 0.9881 - val_loss: 1.0534 - val_mse: 1.0534
Epoch 42/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9867 - mse: 0.9867 - val_loss: 1.0526 - val_mse: 1.0526
Epoch 43/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9853 - mse: 0.9853 - val_loss: 1.0519 - val_mse: 1.0519
Epoch 44/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9840 - mse: 0.9840 - val_loss: 1.0512 - val_mse: 1.0512
Epoch 45/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9828 - mse: 0.9828 - val_loss: 1.0505 - val_mse: 1.0505
Epoch 46/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9816 - mse: 0.9816 - val_loss: 1.0498 - val_mse: 1.0498
Epoch 47/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9805 - mse: 0.9805 - val_loss: 1.0492 - val_mse: 1.0492
Epoch 48/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9795 - mse: 0.9795 - val_loss: 1.0487 - val_mse: 1.0487
Epoch 49/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9782 - mse: 0.9782 - val_loss: 1.0481 - val_mse: 1.0481
Epoch 50/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9771 - mse: 0.9771 - val_loss: 1.0474 - val_mse: 1.0474
Epoch 51/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9759 - mse: 0.9759 - val_loss: 1.0470 - val_mse: 1.0470
Epoch 52/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9749 - mse: 0.9749 - val_loss: 1.0466 - val_mse: 1.0466
Epoch 53/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9739 - mse: 0.9739 - val_loss: 1.0460 - val_mse: 1.0460
Epoch 54/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9730 - mse: 0.9730 - val_loss: 1.0454 - val_mse: 1.0454
Epoch 55/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9721 - mse: 0.9721 - val_loss: 1.0449 - val_mse: 1.0449
Epoch 56/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9711 - mse: 0.9711 - val_loss: 1.0444 - val_mse: 1.0444
Epoch 57/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9702 - mse: 0.9702 - val_loss: 1.0440 - val_mse: 1.0440
Epoch 58/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9694 - mse: 0.9694 - val_loss: 1.0436 - val_mse: 1.0436
Epoch 59/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9685 - mse: 0.9685 - val_loss: 1.0429 - val_mse: 1.0429
Epoch 60/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9676 - mse: 0.9676 - val_loss: 1.0425 - val_mse: 1.0425
Epoch 61/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9667 - mse: 0.9667 - val_loss: 1.0420 - val_mse: 1.0420
Epoch 62/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9659 - mse: 0.9659 - val_loss: 1.0411 - val_mse: 1.0411
Epoch 63/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9650 - mse: 0.9650 - val_loss: 1.0406 - val_mse: 1.0406
Epoch 64/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9641 - mse: 0.9641 - val_loss: 1.0401 - val_mse: 1.0401
Epoch 65/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9633 - mse: 0.9633 - val_loss: 1.0394 - val_mse: 1.0394
Epoch 66/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9625 - mse: 0.9625 - val_loss: 1.0387 - val_mse: 1.0387
Epoch 67/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9618 - mse: 0.9618 - val_loss: 1.0381 - val_mse: 1.0381
Epoch 68/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9611 - mse: 0.9611 - val_loss: 1.0374 - val_mse: 1.0374
Epoch 69/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9604 - mse: 0.9604 - val_loss: 1.0368 - val_mse: 1.0368
Epoch 70/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9597 - mse: 0.9597 - val_loss: 1.0362 - val_mse: 1.0362
Epoch 71/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9589 - mse: 0.9589 - val_loss: 1.0358 - val_mse: 1.0358
Epoch 72/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9582 - mse: 0.9582 - val_loss: 1.0354 - val_mse: 1.0354
Epoch 73/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9575 - mse: 0.9575 - val_loss: 1.0351 - val_mse: 1.0351
Epoch 74/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9568 - mse: 0.9568 - val_loss: 1.0346 - val_mse: 1.0346
Epoch 75/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9561 - mse: 0.9561 - val_loss: 1.0342 - val_mse: 1.0342
Epoch 76/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9555 - mse: 0.9555 - val_loss: 1.0339 - val_mse: 1.0339
Epoch 77/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9549 - mse: 0.9549 - val_loss: 1.0336 - val_mse: 1.0336
Epoch 78/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9542 - mse: 0.9542 - val_loss: 1.0329 - val_mse: 1.0329
Epoch 79/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9537 - mse: 0.9537 - val_loss: 1.0326 - val_mse: 1.0326
Epoch 80/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9531 - mse: 0.9531 - val_loss: 1.0323 - val_mse: 1.0323
Epoch 81/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9525 - mse: 0.9525 - val_loss: 1.0318 - val_mse: 1.0318
Epoch 82/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9518 - mse: 0.9518 - val_loss: 1.0313 - val_mse: 1.0313
Epoch 83/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9512 - mse: 0.9512 - val_loss: 1.0310 - val_mse: 1.0310
Epoch 84/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9505 - mse: 0.9505 - val_loss: 1.0306 - val_mse: 1.0306
Epoch 85/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9500 - mse: 0.9500 - val_loss: 1.0302 - val_mse: 1.0302
Epoch 86/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9494 - mse: 0.9494 - val_loss: 1.0298 - val_mse: 1.0298
Epoch 87/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9488 - mse: 0.9488 - val_loss: 1.0293 - val_mse: 1.0293
Epoch 88/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9483 - mse: 0.9483 - val_loss: 1.0291 - val_mse: 1.0291
Epoch 89/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9478 - mse: 0.9478 - val_loss: 1.0287 - val_mse: 1.0287
Epoch 90/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9472 - mse: 0.9472 - val_loss: 1.0283 - val_mse: 1.0283
Epoch 91/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9466 - mse: 0.9466 - val_loss: 1.0280 - val_mse: 1.0280
Epoch 92/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9462 - mse: 0.9462 - val_loss: 1.0278 - val_mse: 1.0278
Epoch 93/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9457 - mse: 0.9457 - val_loss: 1.0274 - val_mse: 1.0274
Epoch 94/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9451 - mse: 0.9451 - val_loss: 1.0269 - val_mse: 1.0269
Epoch 95/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9446 - mse: 0.9446 - val_loss: 1.0267 - val_mse: 1.0267
Epoch 96/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9441 - mse: 0.9441 - val_loss: 1.0262 - val_mse: 1.0262
Epoch 97/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9436 - mse: 0.9436 - val_loss: 1.0258 - val_mse: 1.0258
Epoch 98/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9431 - mse: 0.9431 - val_loss: 1.0254 - val_mse: 1.0254
Epoch 99/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9426 - mse: 0.9426 - val_loss: 1.0250 - val_mse: 1.0250
Epoch 100/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9421 - mse: 0.9421 - val_loss: 1.0247 - val_mse: 1.0247
Epoch 101/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9416 - mse: 0.9416 - val_loss: 1.0244 - val_mse: 1.0244
Epoch 102/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9411 - mse: 0.9411 - val_loss: 1.0241 - val_mse: 1.0241
Epoch 103/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9407 - mse: 0.9407 - val_loss: 1.0237 - val_mse: 1.0237
Epoch 104/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9402 - mse: 0.9402 - val_loss: 1.0233 - val_mse: 1.0233
Epoch 105/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9398 - mse: 0.9398 - val_loss: 1.0229 - val_mse: 1.0229
Epoch 106/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9393 - mse: 0.9393 - val_loss: 1.0226 - val_mse: 1.0226
Epoch 107/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9389 - mse: 0.9389 - val_loss: 1.0223 - val_mse: 1.0223
Epoch 108/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9384 - mse: 0.9384 - val_loss: 1.0221 - val_mse: 1.0221
Epoch 109/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9379 - mse: 0.9379 - val_loss: 1.0217 - val_mse: 1.0217
Epoch 110/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9375 - mse: 0.9375 - val_loss: 1.0213 - val_mse: 1.0213
Epoch 111/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9371 - mse: 0.9371 - val_loss: 1.0212 - val_mse: 1.0212
Epoch 112/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9366 - mse: 0.9366 - val_loss: 1.0209 - val_mse: 1.0209
Epoch 113/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9363 - mse: 0.9363 - val_loss: 1.0206 - val_mse: 1.0206
Epoch 114/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9358 - mse: 0.9358 - val_loss: 1.0201 - val_mse: 1.0201
Epoch 115/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9354 - mse: 0.9354 - val_loss: 1.0198 - val_mse: 1.0198
Epoch 116/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9350 - mse: 0.9350 - val_loss: 1.0194 - val_mse: 1.0194
Epoch 117/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9346 - mse: 0.9346 - val_loss: 1.0192 - val_mse: 1.0192
Epoch 118/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9342 - mse: 0.9342 - val_loss: 1.0188 - val_mse: 1.0188
Epoch 119/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9338 - mse: 0.9338 - val_loss: 1.0182 - val_mse: 1.0182
Epoch 120/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9334 - mse: 0.9334 - val_loss: 1.0182 - val_mse: 1.0182
Epoch 121/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9330 - mse: 0.9330 - val_loss: 1.0180 - val_mse: 1.0180
Epoch 122/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9327 - mse: 0.9327 - val_loss: 1.0176 - val_mse: 1.0176
Epoch 123/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9322 - mse: 0.9322 - val_loss: 1.0173 - val_mse: 1.0173
Epoch 124/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9317 - mse: 0.9317 - val_loss: 1.0170 - val_mse: 1.0170
Epoch 125/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9313 - mse: 0.9313 - val_loss: 1.0167 - val_mse: 1.0167
Epoch 126/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9309 - mse: 0.9309 - val_loss: 1.0163 - val_mse: 1.0163
Epoch 127/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9304 - mse: 0.9304 - val_loss: 1.0161 - val_mse: 1.0161
Epoch 128/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9300 - mse: 0.9300 - val_loss: 1.0159 - val_mse: 1.0159
Epoch 129/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9296 - mse: 0.9296 - val_loss: 1.0156 - val_mse: 1.0156
Epoch 130/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9292 - mse: 0.9292 - val_loss: 1.0153 - val_mse: 1.0153
Epoch 131/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9288 - mse: 0.9288 - val_loss: 1.0150 - val_mse: 1.0150
Epoch 132/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9284 - mse: 0.9284 - val_loss: 1.0147 - val_mse: 1.0147
Epoch 133/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9279 - mse: 0.9279 - val_loss: 1.0144 - val_mse: 1.0144
Epoch 134/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9276 - mse: 0.9276 - val_loss: 1.0144 - val_mse: 1.0144
Epoch 135/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9272 - mse: 0.9272 - val_loss: 1.0141 - val_mse: 1.0141
Epoch 136/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9268 - mse: 0.9268 - val_loss: 1.0139 - val_mse: 1.0139
Epoch 137/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9264 - mse: 0.9264 - val_loss: 1.0138 - val_mse: 1.0138
Epoch 138/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9260 - mse: 0.9260 - val_loss: 1.0136 - val_mse: 1.0136
Epoch 139/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9257 - mse: 0.9257 - val_loss: 1.0135 - val_mse: 1.0135
Epoch 140/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9252 - mse: 0.9252 - val_loss: 1.0132 - val_mse: 1.0132
Epoch 141/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9249 - mse: 0.9249 - val_loss: 1.0130 - val_mse: 1.0130
Epoch 142/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9245 - mse: 0.9245 - val_loss: 1.0128 - val_mse: 1.0128
Epoch 143/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9243 - mse: 0.9243 - val_loss: 1.0125 - val_mse: 1.0125
Epoch 144/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9238 - mse: 0.9238 - val_loss: 1.0125 - val_mse: 1.0125
Epoch 145/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9234 - mse: 0.9234 - val_loss: 1.0121 - val_mse: 1.0121
Epoch 146/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9229 - mse: 0.9229 - val_loss: 1.0118 - val_mse: 1.0118
Epoch 147/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9226 - mse: 0.9226 - val_loss: 1.0118 - val_mse: 1.0118
Epoch 148/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9222 - mse: 0.9222 - val_loss: 1.0117 - val_mse: 1.0117
Epoch 149/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9218 - mse: 0.9218 - val_loss: 1.0115 - val_mse: 1.0115
Epoch 150/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9214 - mse: 0.9214 - val_loss: 1.0114 - val_mse: 1.0114
Epoch 151/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9211 - mse: 0.9211 - val_loss: 1.0112 - val_mse: 1.0112
Epoch 152/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9207 - mse: 0.9207 - val_loss: 1.0114 - val_mse: 1.0114
Epoch 153/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9203 - mse: 0.9203 - val_loss: 1.0111 - val_mse: 1.0111
Epoch 154/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9199 - mse: 0.9199 - val_loss: 1.0110 - val_mse: 1.0110
Epoch 155/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9195 - mse: 0.9195 - val_loss: 1.0108 - val_mse: 1.0108
Epoch 156/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9192 - mse: 0.9192 - val_loss: 1.0108 - val_mse: 1.0108
Epoch 157/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9189 - mse: 0.9189 - val_loss: 1.0108 - val_mse: 1.0108
Epoch 158/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9184 - mse: 0.9184 - val_loss: 1.0108 - val_mse: 1.0108
Epoch 159/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9180 - mse: 0.9180 - val_loss: 1.0107 - val_mse: 1.0107
Epoch 160/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9177 - mse: 0.9177 - val_loss: 1.0105 - val_mse: 1.0105
Epoch 161/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9173 - mse: 0.9173 - val_loss: 1.0104 - val_mse: 1.0104
Epoch 162/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9169 - mse: 0.9169 - val_loss: 1.0106 - val_mse: 1.0106
Epoch 163/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9166 - mse: 0.9166 - val_loss: 1.0104 - val_mse: 1.0104
Epoch 164/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9162 - mse: 0.9162 - val_loss: 1.0104 - val_mse: 1.0104
Epoch 165/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9159 - mse: 0.9159 - val_loss: 1.0103 - val_mse: 1.0103
Epoch 166/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9155 - mse: 0.9155 - val_loss: 1.0104 - val_mse: 1.0104
Epoch 167/1000
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9152 - mse: 0.9152 - val_loss: 1.0103 - val_mse: 1.0103
Epoch 168/1000

In [931]:
model.evaluate(X_test,y_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2694 - mse: 1.2694

[1.2693655490875244, 1.2693655490875244]

In [932]:
y_pred = model.predict(X_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

In [ ]:
r2_score(y_pred,y_test)
#CORRECCIÓN: Para poder valorar el resultado tendrías que haber comparado con un árbol de decisión o con un random forest.

-16.950468750428353

## Ejercicio 2

In [934]:
folders = listdir("/home/ciabd03/Descargas/cartas/")

photos = []
labels = []

for idx, folder in enumerate(folders):
    for file in listdir("/home/ciabd03/Descargas/cartas/"+folder):
        photo = load_img("/home/ciabd03/Descargas/cartas/"+folder+"/"+file, color_mode="grayscale",target_size=(117,117))
        photo = img_to_array(photo)
        photos.append(photo)
        labels.append(float(idx))
        del photo

    print(folder)
    print(idx)

six of clubs
0
three of clubs
1
jack of clubs
2
five of spades
3
jack of diamonds
4
three of spades
5
two of diamonds
6
jack of spades
7
two of clubs
8
two of hearts
9
ace of diamonds
10
jack of hearts
11
joker
12
eight of clubs
13
three of diamonds
14
king of clubs
15
seven of diamonds
16
ten of clubs
17
five of clubs
18
six of spades
19
queen of hearts
20
queen of spades
21
king of diamonds
22
ten of diamonds
23
seven of spades
24
queen of diamonds
25
ten of hearts
26
two of spades
27
seven of hearts
28
ace of clubs
29
three of hearts
30
five of diamonds
31
six of hearts
32
four of spades
33
king of hearts
34
ace of hearts
35
nine of spades
36
king of spades
37
four of hearts
38
ace of spades
39
five of hearts
40
four of clubs
41
nine of diamonds
42
nine of clubs
43
seven of clubs
44
ten of spades
45
six of diamonds
46
queen of clubs
47
eight of hearts
48
eight of diamonds
49
nine of hearts
50
eight of spades
51
four of diamonds
52

In [935]:
X = np.asarray(photos)
y = np.asarray(labels)

In [936]:
X.shape

(7624, 117, 117, 1)

In [937]:
X = X.reshape(7624,-1)

In [ ]:
X = X/255.0
#CORRECCIÓN: Carga de datos OK.

In [939]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X,y,test_size=0.1,random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full,y_train_full,test_size=0.1,random_state=42)

In [940]:
X_train.shape[1:]

(13689,)

In [941]:
""" model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=X_train.shape[1:]))
model.add(keras.layers.Dense(2000,activation="relu"))
model.add(keras.layers.Dense(500,activation="relu"))
model.add(keras.layers.Dense(150,activation="relu"))
model.add(keras.layers.Dense(53,activation="softmax")) """

' model = keras.models.Sequential()\nmodel.add(keras.layers.Flatten(input_shape=X_train.shape[1:]))\nmodel.add(keras.layers.Dense(2000,activation="relu"))\nmodel.add(keras.layers.Dense(500,activation="relu"))\nmodel.add(keras.layers.Dense(150,activation="relu"))\nmodel.add(keras.layers.Dense(53,activation="softmax")) '

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=X_train.shape[1:]))
model.add(keras.layers.Dense(1500,activation="relu"))
model.add(keras.layers.Dense(250,activation="relu"))
model.add(keras.layers.Dense(75,activation="relu"))
model.add(keras.layers.Dense(53,activation="softmax"))
#CORRECCIÓN: Ojo, en cuanto al diseño, todo bien, salvo que has hecho reshape y flatten. Cuidado con estas cosas... en este 
#caso no va a suponer un error pero en otros casos despistes similares pueden suponer problemas.
# En cuanto al dimensionamiento, 1500 es poco, no llega al 11%. De primeras habría que poner más.

' model = keras.models.Sequential()\nmodel.add(keras.layers.Flatten(input_shape=X_train.shape[1:]))\nmodel.add(keras.layers.Dense(1500,activation="relu"))\nmodel.add(keras.layers.Dense(250,activation="relu"))\nmodel.add(keras.layers.Dense(75,activation="relu"))\nmodel.add(keras.layers.Dense(53,activation="softmax")) '

In [ ]:
""" model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=X_train.shape[1:]))
model.add(keras.layers.Dense(2500,activation="relu"))
model.add(keras.layers.Dense(500,activation="relu"))
model.add(keras.layers.Dense(53,activation="softmax")) """

/home/ciabd03/anaconda3/lib/python3.13/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [944]:
model.compile(loss="sparse_categorical_crossentropy", optimizer=keras.optimizers.SGD(learning_rate=0.0005), metrics=["accuracy"])

In [945]:
early_stopping_cb = keras.callbacks.EarlyStopping(patience=5,restore_best_weights=True)

In [946]:
history = model.fit(X_train,y_train, epochs=1000,validation_data=(X_val,y_val),callbacks=[early_stopping_cb])

Epoch 1/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.0460 - loss: 3.9276 - val_accuracy: 0.0684 - val_loss: 3.8150
Epoch 2/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.0973 - loss: 3.7369 - val_accuracy: 0.1310 - val_loss: 3.6623
Epoch 3/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.1328 - loss: 3.6097 - val_accuracy: 0.1557 - val_loss: 3.5633
Epoch 4/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.1582 - loss: 3.5016 - val_accuracy: 0.1528 - val_loss: 3.4866
Epoch 5/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.1757 - loss: 3.4104 - val_accuracy: 0.1689 - val_loss: 3.4190
Epoch 6/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.1931 - loss: 3.3280 - val_accuracy: 0.1689 - val_loss: 3.3669
Epoch 7/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.2034 - loss: 3.2627 - val_accuracy: 0.2154 - val_loss: 3.2990
Epoch 8/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.2178 - loss: 3.1964 - val_accuracy: 0.2023 - val_loss: 3.2546
Epoch 9/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.2253 - loss: 3.1429 - val_accuracy: 0.2256 - val_loss: 3.2030
Epoch 10/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.2371 - loss: 3.0893 - val_accuracy: 0.2213 - val_loss: 3.1738
Epoch 11/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.2512 - loss: 3.0440 - val_accuracy: 0.2183 - val_loss: 3.1333
Epoch 12/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.2556 - loss: 3.0000 - val_accuracy: 0.2489 - val_loss: 3.1054
Epoch 13/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.2700 - loss: 2.9573 - val_accuracy: 0.2344 - val_loss: 3.0768
Epoch 14/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.2836 - loss: 2.9200 - val_accuracy: 0.2809 - val_loss: 3.0357
Epoch 15/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.2891 - loss: 2.8847 - val_accuracy: 0.2751 - val_loss: 3.0180
Epoch 16/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.2988 - loss: 2.8528 - val_accuracy: 0.2678 - val_loss: 2.9927
Epoch 17/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3052 - loss: 2.8223 - val_accuracy: 0.2853 - val_loss: 2.9636
Epoch 18/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3181 - loss: 2.7919 - val_accuracy: 0.2897 - val_loss: 2.9575
Epoch 19/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.3259 - loss: 2.7661 - val_accuracy: 0.2882 - val_loss: 2.9498
Epoch 20/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 53ms/step - accuracy: 0.3364 - loss: 2.7398 - val_accuracy: 0.2897 - val_loss: 2.9485
Epoch 21/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3401 - loss: 2.7153 - val_accuracy: 0.2824 - val_loss: 2.9099
Epoch 22/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3482 - loss: 2.6900 - val_accuracy: 0.3086 - val_loss: 2.9066
Epoch 23/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3617 - loss: 2.6659 - val_accuracy: 0.3130 - val_loss: 2.8774
Epoch 24/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3628 - loss: 2.6450 - val_accuracy: 0.2911 - val_loss: 2.8679
Epoch 25/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 53ms/step - accuracy: 0.3733 - loss: 2.6199 - val_accuracy: 0.3246 - val_loss: 2.8459
Epoch 26/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.3829 - loss: 2.5974 - val_accuracy: 0.3100 - val_loss: 2.8540
Epoch 27/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3840 - loss: 2.5750 - val_accuracy: 0.3348 - val_loss: 2.8316
Epoch 28/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.3907 - loss: 2.5573 - val_accuracy: 0.3348 - val_loss: 2.8110
Epoch 29/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 52ms/step - accuracy: 0.4017 - loss: 2.5403 - val_accuracy: 0.3100 - val_loss: 2.8143
Epoch 30/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.4051 - loss: 2.5187 - val_accuracy: 0.3173 - val_loss: 2.8006
Epoch 31/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.4088 - loss: 2.5024 - val_accuracy: 0.3246 - val_loss: 2.8022
Epoch 32/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - accuracy: 0.4138 - loss: 2.4814 - val_accuracy: 0.3377 - val_loss: 2.7847
Epoch 33/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.4172 - loss: 2.4637 - val_accuracy: 0.3231 - val_loss: 2.7900
Epoch 34/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 52ms/step - accuracy: 0.4268 - loss: 2.4463 - val_accuracy: 0.3086 - val_loss: 2.7654
Epoch 35/1000
193/193 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.4250 - loss: 2.4309 - val_accuracy: 0.3115 - val_loss: 2.7677
Epoch 36/1000
 74/193 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.4200 - loss: 2.4361

KeyboardInterrupt:

In [ ]:
model.evaluate(X_test,y_test)
#CORRECCIÓN: De los intentos que has hecho no veo los resultados. 
# No has usado métodos para valorar los resultados.

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3604 - loss: 2.5242

[2.5242297649383545, 0.3604193925857544]